### ISSUE TITLE
How should @types be integrated into search and filters?

### ISSUE THREAD

**Issue by kenjinp** [BlueBrain/nexus-explorer#44]
The design currently takes into consideration only schemas in terms of filtering content. 

For example, you may filter for all views in a project, or all resources that have the schema ReconstructedPatchedCell

Will it be necessary to filter by @type as well in some capacity?

connects #39

**Comment by annakristinkaufmann** [comment]
From my perspective, this is definitely relevant as the type of data is what a data consumer / scientist often cares about. I can foresee the use case of wanting to filter for a specific type of data - irrespective of which schema it was validated against - as a very common one!

**Comment by mdupont** [comment]
I agree with @annakristinkaufmann. I see @types becoming one of the main filters in the Search and other end-user focused apps. So it makes sense that advanced-user apps like Explorer provide this filter as well, so that data integrator can better check the data based on the same criteria than end users.

**Comment by mdupont** [comment]
This issue was moved to BlueBrain/nexus#146
